src/Entity/BesoinRole.php
<?php

namespace App\Entity;

use App\Repository\BesoinRoleRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: BesoinRoleRepository::class)]
#[Broadcast]
class BesoinRole
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $nb_jours = null;

    #[ORM\ManyToOne(inversedBy: 'besoinRoles')]
    private ?Role $role = null;

    #[ORM\ManyToOne(inversedBy: 'besoin_role')]
    private ?Offre $offre = null;

    #[ORM\Column]
    private ?int $nb_jours_estime_min = null;

    #[ORM\Column]
    private ?int $nb_jours_estime_max = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbJours(): ?int
    {
        return $this->nb_jours;
    }

    public function setNbJours(int $nb_jours): static
    {
        $this->nb_jours = $nb_jours;

        return $this;
    }

    public function getRole(): ?Role
    {
        return $this->role;
    }

    public function setRole(?Role $role): static
    {
        $this->role = $role;

        return $this;
    }

    public function getOffre(): ?Offre
    {
        return $this->offre;
    }

    public function setOffre(?Offre $offre): static
    {
        $this->offre = $offre;

        return $this;
    }

    public function getNbJoursEstimeMin(): ?int
    {
        return $this->nb_jours_estime_min;
    }

    public function setNbJoursEstimeMin(int $nb_jours_estime_min): static
    {
        $this->nb_jours_estime_min = $nb_jours_estime_min;

        return $this;
    }

    public function getNbJoursEstimeMax(): ?int
    {
        return $this->nb_jours_estime_max;
    }

    public function setNbJoursEstimeMax(int $nb_jours_estime_max): static
    {
        $this->nb_jours_estime_max = $nb_jours_estime_max;

        return $this;
    }
}

src/Entity/Offre.php
<?php

namespace App\Entity;

use App\Repository\OffreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: OffreRepository::class)]
#[Broadcast]
class Offre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $libelle = null;

    #[ORM\Column(length: 255)]
    private ?string $description_courte = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_longue = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: '0')]
    private ?string $prix_min = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: '0')]
    private ?string $prix_max = null;

    #[ORM\Column]
    private ?bool $visible = null;

    #[ORM\Column]
    private ?int $deadline = null;

    #[ORM\ManyToOne(inversedBy: 'offres')]
    private ?Game $game = null;

    #[ORM\OneToMany(mappedBy: 'offre', targetEntity: BesoinRole::class, cascade: ['persist', 'remove'])]
    private Collection $besoin_role;

    // src/Entity/Offre.php

    #[ORM\ManyToOne(targetEntity: TypeOffre::class, inversedBy: 'offres')]
    private ?TypeOffre $type_offre = null;

    #[ORM\ManyToMany(targetEntity: Equipe::class, mappedBy: 'offres')]
    private Collection $equipes;

    #[ORM\OneToMany(mappedBy: 'offre', targetEntity: Proposition::class)]
    private Collection $propositions;

    #[ORM\Column]
    private ?int $accompte = null;

    #[ORM\OneToMany(mappedBy: 'offre', targetEntity: Projet::class)]
    private Collection $projets;

    public function getTypeOffre(): ?TypeOffre
    {
        return $this->type_offre;
    }

    public function setTypeOffre(?TypeOffre $type_offre): static
    {
        $this->type_offre = $type_offre;

        return $this;
    }

    public function __construct()
    {
        $this->besoin_role = new ArrayCollection();
        $this->equipes = new ArrayCollection();
        $this->propositions = new ArrayCollection();
        $this->projets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): static
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getDescriptionCourte(): ?string
    {
        return $this->description_courte;
    }

    public function setDescriptionCourte(string $description_courte): static
    {
        $this->description_courte = $description_courte;

        return $this;
    }

    public function getDescriptionLongue(): ?string
    {
        return $this->description_longue;
    }

    public function setDescriptionLongue(string $description_longue): static
    {
        $this->description_longue = $description_longue;

        return $this;
    }

    public function getPrixMin(): ?string
    {
        return $this->prix_min;
    }

    public function setPrixMin(string $prix_min): static
    {
        $this->prix_min = $prix_min;

        return $this;
    }

    public function getPrixMax(): ?string
    {
        return $this->prix_max;
    }

    public function setPrixMax(string $prix_max): static
    {
        $this->prix_max = $prix_max;

        return $this;
    }

    public function isVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): static
    {
        $this->visible = $visible;

        return $this;
    }

    public function getDeadline(): ?int
    {
        return $this->deadline;
    }

    public function setDeadline(int $deadline): static
    {
        $this->deadline = $deadline;

        return $this;
    }

    public function getGame(): ?Game
    {
        return $this->game;
    }

    public function setGame(?Game $game): static
    {
        $this->game = $game;

        return $this;
    }

    /**
     * @return Collection<int, BesoinRole>
     */
    public function getBesoinRole(): Collection
    {
        return $this->besoin_role;
    }

    public function addBesoinRole(BesoinRole $besoinRole): static
    {
        if (!$this->besoin_role->contains($besoinRole)) {
            $this->besoin_role->add($besoinRole);
            $besoinRole->setOffre($this);
        }

        return $this;
    }

    public function removeBesoinRole(BesoinRole $besoinRole): static
    {
        if ($this->besoin_role->removeElement($besoinRole)) {
            // set the owning side to null (unless already changed)
            if ($besoinRole->getOffre() === $this) {
                $besoinRole->setOffre(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Equipe>
     */
    public function getEquipes(): Collection
    {
        return $this->equipes;
    }

    public function addEquipe(Equipe $equipe): static
    {
        if (!$this->equipes->contains($equipe)) {
            $this->equipes->add($equipe);
            $equipe->addOffre($this);
        }

        return $this;
    }

    public function removeEquipe(Equipe $equipe): static
    {
        if ($this->equipes->removeElement($equipe)) {
            $equipe->removeOffre($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Proposition>
     */
    public function getPropositions(): Collection
    {
        return $this->propositions;
    }

    public function addProposition(Proposition $proposition): static
    {
        if (!$this->propositions->contains($proposition)) {
            $this->propositions->add($proposition);
            $proposition->setOffre($this);
        }

        return $this;
    }

    public function removeProposition(Proposition $proposition): static
    {
        if ($this->propositions->removeElement($proposition)) {
            // set the owning side to null (unless already changed)
            if ($proposition->getOffre() === $this) {
                $proposition->setOffre(null);
            }
        }

        return $this;
    }

    public function getAccompte(): ?int
    {
        return $this->accompte;
    }

    public function setAccompte(int $accompte): static
    {
        $this->accompte = $accompte;

        return $this;
    }

    /**
     * @return Collection<int, Projet>
     */
    public function getProjets(): Collection
    {
        return $this->projets;
    }

    public function addProjet(Projet $projet): static
    {
        if (!$this->projets->contains($projet)) {
            $this->projets->add($projet);
            $projet->setOffre($this);
        }

        return $this;
    }

    public function removeProjet(Projet $projet): static
    {
        if ($this->projets->removeElement($projet)) {
            // set the owning side to null (unless already changed)
            if ($projet->getOffre() === $this) {
                $projet->setOffre(null);
            }
        }

        return $this;
    }
}

src/Controller/Phase1B/JoueurPhase1BController.php
<?php

namespace App\Controller\Phase1B;

use App\Entity\Game;
use App\Form\PropositionType;
use App\Repository\OffreRepository;
use App\Repository\PropositionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\Mercure\HubInterface;
use Symfony\Component\Mercure\Update;

class JoueurPhase1BController extends AbstractController
{
    public function __construct(
        private HubInterface $hub,
        protected PropositionRepository $propositionRepository,
        protected OffreRepository $offreRepository,
        private readonly RequestStack $session,
    )
    {
    }

    public function index(
        ?Game $game,
        ?int $offreId
    ): void
    {
        // récupérer toutes les offres de la game avec visible = true
        $offres = $game->getOffres()->filter(function ($offre) {
            return $offre->isVisible() === true;
        });

        // créer un formulaire pour chaque proposition
        $forms = [];
        foreach ($offres as $offre) {
            foreach ($offre->getPropositions() as $proposition) {
                $forms[$offre->getId()][$proposition->getEquipe()->getId()] = $this->createForm(PropositionType::class, $proposition, ['game'=>$game])->createView();
            }
        }

        // récupérer toutes les équipes de la game
        $equipes = $game->getEquipes();

        if ($offreId !== null) {
            $offreUpdated = $this->offreRepository->find($offreId);
        } else {
            $offreUpdated = $offres[0] ?? null;
        }

        // envoyer une mise à jour Mercure pour chaque équipe
        foreach ($equipes as $equipe) {
            $this->hub->publish(new Update(
                'game-joueur/' . $game->getId() . '/equipe/' . $equipe->getId(),
                $this->renderView('phase1b/joueur_phase1b.stream.html.twig', [
                    'game' => $game,
                    'equipe' => $equipe,
                    'offres' => $offres,
                    'forms' => $forms,
                    'offreUpdated' => $offreUpdated ?? null,
                ]),
                false
            ));
        }
    }
}

src/Controller/Phase1B/MaitrePhase1BController.php
<?php

namespace App\Controller\Phase1B;

use App\Entity\Game;
use App\Repository\OffreRepository;
use App\Repository\PropositionRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mercure\HubInterface;
use Symfony\Component\Mercure\Update;
use Symfony\Component\Routing\Annotation\Route;

class MaitrePhase1BController extends AbstractController
{
    public function __construct(
        private HubInterface    $hub,
        private UserRepository  $userRepository,
        private OffreRepository $offreRepository,
    )
    {
    }

//    #[Route('/maitre/phase1/b', name: 'app_maitre_phase1_b')]
    public function index(?Game $game, array $offres, array $equipes, ?int $offreId): void
    {
        $maitres = $this->userRepository->findByGameAndRole($game, 'ROLE_MAITRE');

        if ($offreId !== null) {
            $offreUpdated = $this->offreRepository->find($offreId);
        } else {
            $offreUpdated = $offres[0] ?? null;
        }

        dump($offreUpdated);

        foreach ($maitres as $maitre) {
            $this->hub->publish(new Update(
                'game-maitre/' . $maitre->getId(),
                $this->renderView('phase1b/maitre_phase1b.stream.html.twig', [
                    'game' => $game,
                    'equipes' => $equipes,
                    'offres' => $offres,
                    'maitre' => $maitre,
                    'offreUpdated' => $offreUpdated ?? null,
                ]),
                false
            ));
        }
    }
}

templates/phase1b/joueur_phase1b.stream.html.twig
<turbo-stream action="replace" target="phase-joueur-{{ game.id }}">
    <template>
        <div id="phase-joueur-{{ game.id }}" {{ turbo_stream_listen('game-joueur/'~game.id~'/equipe/'~equipe.id) }}>
            <h2>Phase : {{ game.phase }}</h2>
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                {% for offre in offres %}
                    <li class="nav-item" role="presentation">
                        <a class="nav-link {% if offreUpdated is defined and offreUpdated == offre %}active{% elseif offreUpdated is not defined and loop.first %}active{% elseif offreUpdated is defined and offreUpdated is null and loop.first %}active{% endif %}"
                           id="offre-{{ offre.id }}-tab"
                           data-bs-toggle="tab" href="#offre-{{ offre.id }}" role="tab"
                           aria-controls="offre-{{ offre.id }}"
                           aria-selected="{% if loop.first %}true{% else %}false{% endif %}">{{ offre.libelle }}</a>
                    </li>
                {% endfor %}
            </ul>

            <div class="tab-content" id="myTabContent">
                {% for offre in offres %}
                    <div class="card tab-pane fade {% if offreUpdated is defined and offreUpdated == offre %}show active{% elseif offreUpdated is not defined and loop.first %}show active{% elseif offreUpdated is defined and offreUpdated is null and loop.first %}show active{% endif %}"
                         id="offre-{{ offre.id }}"
                         role="tabpanel" aria-labelledby="offre-{{ offre.id }}-tab">
                        <div class="card-body">


                            {% for message in app.flashes('success') %}
                                <div class="alert alert-success">
                                    {{ message }}
                                </div>
                            {% endfor %}

                            {% for message in app.flashes('error') %}
                                <div class="alert alert-danger">
                                    {{ message }}
                                </div>
                            {% endfor %}


                            <h3>{{ offre.libelle }}</h3>
                            <div class="d-inline-flex gap-1">
                                <em>{{ offre.descriptionCourte|raw }}</em>
                                <em class="link-primary" data-bs-toggle="collapse"
                                    data-bs-target="#collapseExample" aria-expanded="false"
                                    aria-controls="collapseExample">
                                    En savoir plus
                                </em>
                            </div>
                            <div class="collapse" id="collapseExample">
                                <div class="card card-body">
                                    {{ offre.descriptionLongue|raw }}
                                </div>
                            </div>

                            <hr>

                            <ul>
                                {% for besoin in offre.besoinRole %}
                                    <li><span>{{ besoin.role.libelle }}</span>
                                        {{ besoin.nbJoursEstimeMin }} à
                                        {{ besoin.nbJoursEstimeMax }} jours
                                    </li>
                                {% endfor %}
                            </ul>

                            <h4>Budget de l'entreprise</h4>
                            <small>Accompte versé à la signature : {{ offre.accompte }} %</small>
                            <ul>
                                <li>
                                    <i class="fa-solid fa-arrow-down"
                                       style="color: red"></i> {{ offre.prixMin|format_currency('EUR', locale='fr') }}
                                </li>
                                <li>
                                    <i class="fa-solid fa-arrow-up"
                                       style="color: green"></i> {{ offre.prixMax|format_currency('EUR', locale='fr') }}
                                </li>
                            </ul>

                            <h4>Durée du projet</h4>
                            <ul>
                                <li>{{ offre.deadline }} mois</li>
                            </ul>

                            <turbo-frame id="proposition-frame-{{ offre.id }}">
                                {% if equipe is not null %}
                                    {% for proposition in offre.propositions %}
                                        {% if proposition.equipe.id == equipe.id %}

                                            {% if game.pause == true %}
                                                <button class="btn btn-danger disabled">
                                                    Annuler la proposition
                                                </button>
                                            {% else %}
                                                <a href="{{ path('app_proposition_delete', {id:proposition.id}) }}">
                                                    <button class="btn btn-danger">
                                                        Annuler la proposition
                                                    </button>
                                                </a>
                                            {% endif %}

                                            {% if game.pause == true %}
                                                {{ form_start(forms[offre.id][proposition.equipe.id], {'method': 'POST', 'action': path('app_proposition_update', {'id':proposition.id})}) }}
                                                {{ form_row(forms[offre.id][proposition.equipe.id].type, {'attr': {'disabled':'disabled'}}) }}
                                                {{ form_row(forms[offre.id][proposition.equipe.id].prix, {'attr': {'disabled':'disabled'}}) }}
                                                {{ form_row(forms[offre.id][proposition.equipe.id].estimationRoles, {'attr': {'disabled':'disabled'}}) }}
                                            {% else %}
                                                {{ form_start(forms[offre.id][proposition.equipe.id], {'method': 'POST', 'action': path('app_proposition_update', {'id':proposition.id})}) }}
                                                {{ form_row(forms[offre.id][proposition.equipe.id].type) }}
                                                {{ form_row(forms[offre.id][proposition.equipe.id].prix) }}
                                                {{ form_row(forms[offre.id][proposition.equipe.id].estimationRoles) }}
                                            {% endif %}

                                            <button class="btn btn-primary
                                                    {% if game.pause == true %}
                                                    disabled
                                                    {% endif %}"
                                                    {% if game.pause == true %}disabled{% endif %}
                                                    type="submit">Modifier la proposition
                                            </button>

                                            {{ form_end(forms[offre.id][proposition.equipe.id]) }}

                                        {% elseif offre.propositions|filter(e => e.equipe.id == equipe.id)|length == 0 %}

                                            {% if game.pause == true %}
                                                <button class="btn btn-primary disabled">
                                                    Répondre à cette offre
                                                </button>
                                            {% else %}
                                                <a href="{{ path('app_proposition_create', {'offreId':offre.id, 'equipeId':equipe.id}) }}">
                                                    <button class="btn btn-primary">
                                                        Répondre à cette offre
                                                    </button>
                                                </a>
                                            {% endif %}

                                        {% endif %}
                                    {% endfor %}
                                    {% if offre.propositions is empty %}

                                        {% if game.pause == true %}
                                            <button class="btn btn-primary disabled">
                                                Répondre à cette offre
                                            </button>
                                        {% else %}
                                            <a href="{{ path('app_proposition_create', {'offreId':offre.id, 'equipeId':equipe.id}) }}">
                                                <button class="btn btn-primary">
                                                    Répondre à cette offre
                                                </button>
                                            </a>
                                        {% endif %}

                                    {% endif %}
                                {% endif %}
                            </turbo-frame>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="pause" style="border: solid 10px {{ equipe.couleur }}">
                {% if game.pause == true %}
                    <i class="fa-duotone fa-circle-pause fa-3x" style="color: orange"></i>
                {% else %}
                    <i class="fa-duotone fa-circle-play fa-3x" style="color: green"></i>
                {% endif %}
            </div>
        </div>
    </template>
</turbo-stream>

templates/phase1b/maitre_phase1b.stream.html.twig
<turbo-stream action="replace" target="phase">
    <template>
        <div id="phase" {{ turbo_stream_listen('game-maitre/'~maitre.id) }}>
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                {% for offre in offres %}
                    <li class="nav-item" role="presentation">
                        <a class="nav-link {% if offreUpdated is defined and offreUpdated == offre %}active{% elseif offreUpdated is not defined and loop.first %}active{% endif %}"
                           id="offre-{{ offre.id }}-tab"
                           data-bs-toggle="tab" href="#offre-{{ offre.id }}" role="tab"
                           aria-controls="offre-{{ offre.id }}"
                           aria-selected="{% if loop.first %}true{% else %}false{% endif %}">{{ offre.libelle }}</a>
                    </li>
                {% endfor %}
            </ul>

            <div class="tab-content" id="myTabContent">
                {% for offre in offres %}
                    <div class="card tab-pane fade
                    {% if offreUpdated is defined and offreUpdated == offre %}show active{% elseif offreUpdated is not defined and loop.first %}show active{% endif %}"
                         id="offre-{{ offre.id }}"
                         role="tabpanel" aria-labelledby="offre-{{ offre.id }}-tab">
                        <div class="card-body">
                            <h3>{{ offre.libelle }}</h3>
                            <p>
                                {{ offre.typeOffre.libelle }} | {{ offre.prixMin|format_currency('EUR', locale='fr') }}
                                - {{ offre.prixMax|format_currency('EUR', locale='fr') }}
                            </p>
                            <table>
                                <thead>
                                <tr>
                                    <th>Equipe</th>
                                    <th>Type projet</th>
                                    <th>Proposition</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for equipe in equipes %}
                                    {% for proposition in equipe.propositions %}
                                        {% if proposition.offre.id == offre.id %}
                                            <tr>
                                            <td>{{ proposition.equipe.nom }}</td>
                                            {% if proposition.type is not null %}
                                                <td
                                                        {% if proposition.type.libelle == offre.typeOffre.libelle %}
                                                            style="color: green"
                                                        {% else %}
                                                            style="color: red"
                                                        {% endif %}
                                                >{{ proposition.type.libelle }}</td>
                                            {% else %}
                                                <td>Non défini</td>
                                            {% endif %}
                                            {% if proposition.prix is not null %}
                                                <td>{{ proposition.prix|format_currency('EUR', locale='fr') }}</td>
                                            {% else %}
                                                <td>0 €</td>
                                            {% endif %}
                                            <td>
                                                <turbo-frame>
                                                    <a href="{{ path('app_proposition_state', {'id':proposition.id}) }}">
                                                        <button class="btn
                                        {% if proposition.etat == true %}
                                    btn-success">
                                                            Refuser
                                                            {% else %}
                                                                btn-danger">
                                                                Accepter
                                                            {% endif %}
                                                        </button>
                                                    </a>
                                                </turbo-frame>
                                            </td>
                                        {% endif %}
                                    {% endfor %}
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <hr>
            <turbo-frame>
                <table class="table table-striped table-hover table-bordered">
                    <thead>
                    <tr>
                        <th></th>
                        {% for offre in offres %}
                            <th>{{ offre.libelle }}</th>
                        {% endfor %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for equipe in equipes %}
                        <tr>
                            <td>
                                {{ equipe.nom }}
                            </td>
                            {% for offre in offres %}
                                {% for proposition in equipe.propositions %}
                                    {% if proposition.offre.id == offre.id and proposition.etat == true %}
                                        <td>
                                            <span class="badge bg-success">Accepté</span>
                                        </td>
                                    {% elseif proposition.offre.id == offre.id and proposition.etat == false %}
                                        <td>
                                            <span class="badge bg-danger">Refusé</span>
                                        </td>
                                    {% endif %}
                                {% endfor %}
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
            </turbo-frame>

        </div>
    </template>
</turbo-stream>