src/Entity/Equipe.php
<?php

namespace App\Entity;

use App\Repository\EquipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: EquipeRepository::class)]
#[Broadcast]
class Equipe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column]
    private ?int $materiel = 3;

    #[ORM\Column]
    private ?int $materielLoue = 0;

    #[ORM\Column]
    private ?int $materielAchat = 0;

    #[ORM\Column]
    private ?float $produit_ca = 0;

    #[ORM\Column]
    private ?float $benefice = 0;

    #[ORM\Column]
    private ?float $materiel_amortir = 0;

    #[ORM\Column]
    private ?float $materiel_actif = 6000;

    #[ORM\Column]
    private ?float $actif_creance = 0;

    #[ORM\Column]
    private ?float $actif_dispo = 9000;

    #[ORM\Column]
    private ?float $actif_total = 0;

    #[ORM\Column]
    private ?float $passif_capital = 15000;

    #[ORM\Column]
    private ?float $passif_resultat = 0;

    #[ORM\Column]
    private ?float $passif_dette_financiere = 0;

    #[ORM\Column]
    private ?float $passif_dette_fournisseurs = 0;

    #[ORM\Column]
    private ?float $passif_dette_fiscales = 0;

    #[ORM\Column]
    private ?float $passif_decouvert = 0;

    #[ORM\Column]
    private ?float $passif_total = 0;

    #[ORM\Column]
    private ?float $charges_courantes = 0;

    #[ORM\Column]
    private ?float $charges_location = 0;

    #[ORM\Column]
    private ?float $charges_personnel = 0;

    #[ORM\Column]
    private ?float $charges_freelances = 0;

    #[ORM\Column]
    private ?float $charges_impot = 0;

    #[ORM\Column]
    private ?float $charges_amortissements = 0;

    #[ORM\Column]
    private ?float $charges_interet = 0;

    #[ORM\Column]
    private ?float $tresorerie_solde_initial = 0;

    #[ORM\Column]
    private ?float $tresorerie_encaissement = 6000;

    #[ORM\Column]
    private ?float $tresorerie_decaissement = 15000;

    #[ORM\Column]
    private ?float $tresorerie_solde_final = 9000;

    #[ORM\Column]
    private ?float $cumul_charge = 0;

    #[ORM\Column]
    private ?float $cumul_location = 0;

    #[ORM\Column]
    private ?float $cumul_personnel = 0;

    #[ORM\Column]
    private ?float $cumul_freelance = 0;

    #[ORM\Column]
    private ?float $cumul_interets = 0;

    #[ORM\Column]
    private ?float $cumul_impots = 0;

    #[ORM\Column]
    private ?float $cumul_amortissement = 0;

    #[ORM\Column]
    private ?float $cumul_ca = 0;

    #[ORM\Column]
    private ?float $total_charge = 0;

    #[ORM\Column]
    private ?float $total_produit = 0;

    #[ORM\OneToMany(mappedBy: 'equipe', targetEntity: Personnel::class)]
    private Collection $personnels;

    #[ORM\Column]
    private ?int $reputation = 6;

    #[ORM\Column(length: 20)]
    private string $couleur= "75,192,192";

    #[ORM\OneToMany(mappedBy: 'equipe', targetEntity: User::class)]
    private Collection $users;

    #[ORM\ManyToMany(targetEntity: Offre::class, inversedBy: 'equipes')]
    private Collection $offres;

    #[ORM\OneToMany(mappedBy: 'equipe', targetEntity: Proposition::class)]
    private Collection $propositions;

    #[ORM\ManyToOne(inversedBy: 'equipes', cascade: ["persist"])]
    private ?Game $game = null;

    #[ORM\OneToMany(mappedBy: 'equipe', targetEntity: Projet::class)]
    private Collection $projets;

    #[ORM\OneToMany(mappedBy: 'equipe', targetEntity: CapaciteRole::class)]
    private Collection $capaciteRoles;

    #[ORM\OneToMany(mappedBy: 'equipe', targetEntity: Profil::class)]
    private Collection $profils;

    #[ORM\ManyToOne(inversedBy: 'equipe')]
    private ?Surface $surface = null;

    public function __construct()
    {
        $this->personnels = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->offres = new ArrayCollection();
        $this->propositions = new ArrayCollection();
        $this->projets = new ArrayCollection();
        $this->capaciteRoles = new ArrayCollection();
        $this->profils = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function __toString(): string
    {
        return $this->getNom();
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getMateriel(): ?int
    {
        return $this->materiel;
    }

    public function setMateriel(int $materiel): static
    {
        $this->materiel = $materiel;

        return $this;
    }

    public function getMaterielLoue(): ?int
    {
        return $this->materielLoue;
    }

    public function setMaterielLoue(int $materielLoue): static
    {
        $this->materielLoue = $materielLoue;

        return $this;
    }

    public function getMaterielAchat(): ?int
    {
        return $this->materielAchat;
    }

    public function setMaterielAchat(int $materielAchat): static
    {
        $this->materielAchat = $materielAchat;

        return $this;
    }

    public function getProduitCa(): ?float
    {
        return $this->produit_ca;
    }

    public function setProduitCa(float $produit_ca): static
    {
        $this->produit_ca = $produit_ca;

        return $this;
    }

    public function getBenefice(): ?float
    {
        return $this->benefice;
    }

    public function setBenefice(float $benefice): static
    {
        $this->benefice = $benefice;

        return $this;
    }

    public function getMaterielAmortir(): ?float
    {
        return $this->materiel_amortir;
    }

    public function setMaterielAmortir(float $materiel_amortir): static
    {
        $this->materiel_amortir = $materiel_amortir;

        return $this;
    }

    public function getMaterielActif(): ?float
    {
        return $this->materiel_actif;
    }

    public function setMaterielActif(float $materiel_actif): static
    {
        $this->materiel_actif = $materiel_actif;

        return $this;
    }

    public function getActifCreance(): ?float
    {
        return $this->actif_creance;
    }

    public function setActifCreance(float $actif_creance): static
    {
        $this->actif_creance = $actif_creance;

        return $this;
    }

    public function getActifDispo(): ?float
    {
        return $this->actif_dispo;
    }

    public function setActifDispo(float $actif_dispo): static
    {
        $this->actif_dispo = $actif_dispo;

        return $this;
    }

    public function getActifTotal(): ?float
    {
        return $this->actif_total;
    }

    public function setActifTotal(float $actif_total): static
    {
        $this->actif_total = $actif_total;

        return $this;
    }

    public function getPassifCapital(): ?float
    {
        return $this->passif_capital;
    }

    public function setPassifCapital(float $passif_capital): static
    {
        $this->passif_capital = $passif_capital;

        return $this;
    }

    public function getPassifResultat(): ?float
    {
        return $this->passif_resultat;
    }

    public function setPassifResultat(float $passif_resultat): static
    {
        $this->passif_resultat = $passif_resultat;

        return $this;
    }

    public function getPassifDetteFinanciere(): ?float
    {
        return $this->passif_dette_financiere;
    }

    public function setPassifDetteFinanciere(float $passif_dette_financiere): static
    {
        $this->passif_dette_financiere = $passif_dette_financiere;

        return $this;
    }

    public function getPassifDetteFournisseurs(): ?float
    {
        return $this->passif_dette_fournisseurs;
    }

    public function setPassifDetteFournisseurs(float $passif_dette_fournisseurs): static
    {
        $this->passif_dette_fournisseurs = $passif_dette_fournisseurs;

        return $this;
    }

    public function getPassifDetteFiscales(): ?float
    {
        return $this->passif_dette_fiscales;
    }

    public function setPassifDetteFiscales(float $passif_dette_fiscales): static
    {
        $this->passif_dette_fiscales = $passif_dette_fiscales;

        return $this;
    }

    public function getPassifDecouvert(): ?float
    {
        return $this->passif_decouvert;
    }

    public function setPassifDecouvert(float $passif_decouvert): static
    {
        $this->passif_decouvert = $passif_decouvert;

        return $this;
    }

    public function getPassifTotal(): ?float
    {
        return $this->passif_total;
    }

    public function setPassifTotal(float $passif_total): static
    {
        $this->passif_total = $passif_total;

        return $this;
    }

    public function getChargesCourantes(): ?float
    {
        return $this->charges_courantes;
    }

    public function setChargesCourantes(float $charges_courantes): static
    {
        $this->charges_courantes = $charges_courantes;

        return $this;
    }

    public function getChargesLocation(): ?float
    {
        return $this->charges_location;
    }

    public function setChargesLocation(float $charges_location): static
    {
        $this->charges_location = $charges_location;

        return $this;
    }

    public function getChargesPersonnel(): ?float
    {
        return $this->charges_personnel;
    }

    public function setChargesPersonnel(float $charges_personnel): static
    {
        $this->charges_personnel = $charges_personnel;

        return $this;
    }

    public function getChargesFreelances(): ?float
    {
        return $this->charges_freelances;
    }

    public function setChargesFreelances(float $charges_freelances): static
    {
        $this->charges_freelances = $charges_freelances;

        return $this;
    }

    public function getChargesImpot(): ?float
    {

src/Entity/Offre.php
<?php

namespace App\Entity;

use App\Repository\OffreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: OffreRepository::class)]
#[Broadcast]
class Offre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $libelle = null;

    #[ORM\Column(length: 255)]
    private ?string $description_courte = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_longue = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: '0')]
    private ?string $prix_min = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: '0')]
    private ?string $prix_max = null;

    #[ORM\Column]
    private ?bool $visible = null;

    #[ORM\Column]
    private ?int $deadline = null;

    #[ORM\ManyToOne(inversedBy: 'offres')]
    private ?Game $game = null;

    #[ORM\OneToMany(mappedBy: 'offre', targetEntity: BesoinRole::class, cascade: ['persist', 'remove'])]
    private Collection $besoin_role;

    // src/Entity/Offre.php

    #[ORM\ManyToOne(targetEntity: TypeOffre::class, inversedBy: 'offres')]
    private ?TypeOffre $type_offre = null;

    #[ORM\ManyToMany(targetEntity: Equipe::class, mappedBy: 'offres')]
    private Collection $equipes;

    #[ORM\OneToMany(mappedBy: 'offre', targetEntity: Proposition::class)]
    private Collection $propositions;

    #[ORM\Column]
    private ?int $accompte = null;

    #[ORM\OneToMany(mappedBy: 'offre', targetEntity: Projet::class)]
    private Collection $projets;

    public function getTypeOffre(): ?TypeOffre
    {
        return $this->type_offre;
    }

    public function setTypeOffre(?TypeOffre $type_offre): static
    {
        $this->type_offre = $type_offre;

        return $this;
    }

    public function __construct()
    {
        $this->besoin_role = new ArrayCollection();
        $this->equipes = new ArrayCollection();
        $this->propositions = new ArrayCollection();
        $this->projets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): static
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getDescriptionCourte(): ?string
    {
        return $this->description_courte;
    }

    public function setDescriptionCourte(string $description_courte): static
    {
        $this->description_courte = $description_courte;

        return $this;
    }

    public function getDescriptionLongue(): ?string
    {
        return $this->description_longue;
    }

    public function setDescriptionLongue(string $description_longue): static
    {
        $this->description_longue = $description_longue;

        return $this;
    }

    public function getPrixMin(): ?string
    {
        return $this->prix_min;
    }

    public function setPrixMin(string $prix_min): static
    {
        $this->prix_min = $prix_min;

        return $this;
    }

    public function getPrixMax(): ?string
    {
        return $this->prix_max;
    }

    public function setPrixMax(string $prix_max): static
    {
        $this->prix_max = $prix_max;

        return $this;
    }

    public function isVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): static
    {
        $this->visible = $visible;

        return $this;
    }

    public function getDeadline(): ?int
    {
        return $this->deadline;
    }

    public function setDeadline(int $deadline): static
    {
        $this->deadline = $deadline;

        return $this;
    }

    public function getGame(): ?Game
    {
        return $this->game;
    }

    public function setGame(?Game $game): static
    {
        $this->game = $game;

        return $this;
    }

    /**
     * @return Collection<int, BesoinRole>
     */
    public function getBesoinRole(): Collection
    {
        return $this->besoin_role;
    }

    public function addBesoinRole(BesoinRole $besoinRole): static
    {
        if (!$this->besoin_role->contains($besoinRole)) {
            $this->besoin_role->add($besoinRole);
            $besoinRole->setOffre($this);
        }

        return $this;
    }

    public function removeBesoinRole(BesoinRole $besoinRole): static
    {
        if ($this->besoin_role->removeElement($besoinRole)) {
            // set the owning side to null (unless already changed)
            if ($besoinRole->getOffre() === $this) {
                $besoinRole->setOffre(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Equipe>
     */
    public function getEquipes(): Collection
    {
        return $this->equipes;
    }

    public function addEquipe(Equipe $equipe): static
    {
        if (!$this->equipes->contains($equipe)) {
            $this->equipes->add($equipe);
            $equipe->addOffre($this);
        }

        return $this;
    }

    public function removeEquipe(Equipe $equipe): static
    {
        if ($this->equipes->removeElement($equipe)) {
            $equipe->removeOffre($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Proposition>
     */
    public function getPropositions(): Collection
    {
        return $this->propositions;
    }

    public function addProposition(Proposition $proposition): static
    {
        if (!$this->propositions->contains($proposition)) {
            $this->propositions->add($proposition);
            $proposition->setOffre($this);
        }

        return $this;
    }

    public function removeProposition(Proposition $proposition): static
    {
        if ($this->propositions->removeElement($proposition)) {
            // set the owning side to null (unless already changed)
            if ($proposition->getOffre() === $this) {
                $proposition->setOffre(null);
            }
        }

        return $this;
    }

    public function getAccompte(): ?int
    {
        return $this->accompte;
    }

    public function setAccompte(int $accompte): static
    {
        $this->accompte = $accompte;

        return $this;
    }

    /**
     * @return Collection<int, Projet>
     */
    public function getProjets(): Collection
    {
        return $this->projets;
    }

    public function addProjet(Projet $projet): static
    {
        if (!$this->projets->contains($projet)) {
            $this->projets->add($projet);
            $projet->setOffre($this);
        }

        return $this;
    }

    public function removeProjet(Projet $projet): static
    {
        if ($this->projets->removeElement($projet)) {
            // set the owning side to null (unless already changed)
            if ($projet->getOffre() === $this) {
                $projet->setOffre(null);
            }
        }

        return $this;
    }
}

templates/phase1a/joueur_phase1a.stream.html.twig
<turbo-stream action="replace" target="phase-joueur-{{ game.id }}">
    <template>
        <div id="phase-joueur-{{ game.id }}" {{ turbo_stream_listen('game-joueur/'~game.id~'/equipe/'~equipe.id) }}>
            <h2>Phase : {{ game.phase }}</h2>

            <div class="bilan_comptable">
                <table class="table table-bordered no-margin">
                    <thead>
                    <tr>
                        <th colspan="2">Actif</th>
                        <th colspan="2">Passif</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>
                            Matériel
                        </td>
                        <td>
                            {{ equipe.materielActif }} €
                        </td>
                        <td>
                            Capital social
                        </td>
                        <td>
                            {{ equipe.passifCapital }} €
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Créances
                        </td>
                        <td>
                            {{ equipe.actifCreance }} €
                        </td>
                        <td>
                            Résultat
                        </td>
                        <td>
                            {{ equipe.passifResultat }} €
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Disponibilités
                        </td>
                        <td>
                            {{ equipe.actifDispo }} €
                        </td>
                    </tr>
                    <tr>
                        <td>

                        </td>
                        <td>

                        </td>
                        <td>
                            Dettes fournisseurs
                        </td>
                        <td>
                            {{ equipe.passifDetteFournisseurs }} €
                        </td>
                    </tr>
                    <tr>
                        <td>

                        </td>
                        <td>

                        </td>
                        <td>
                            Dettes fiscales et sociales
                        </td>
                        <td>
                            {{ equipe.passifDetteFiscales }} €
                        </td>
                    </tr>
                    <tr>
                        <td>

                        </td>
                        <td>

                        </td>
                        <td>
                            Découvert bancaire
                        </td>
                        <td>
                            {{ equipe.passifDecouvert }} €
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="pause" style="border: solid 10px {{ equipe.couleur }}">
                {% if game.pause == true %}
                    <i class="fa-duotone fa-circle-pause fa-3x" style="color: orange"></i>
                {% else %}
                    <i class="fa-duotone fa-circle-play fa-3x" style="color: green"></i>
                {% endif %}
            </div>
        </div>
    </template>
</turbo-stream>

templates/phase1a/maitre_phase1a.stream.html.twig
<turbo-stream action="replace" target="phase">
    <template>
        <div id="phase" {{ turbo_stream_listen('game-maitre/'~app.user.id) }}>
            <div class="offres1a">
                <table>
                    <thead>
                    <tr>
                        <th>Offre</th>
                        <th>Type</th>
                        <th>Budget</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for offre in offres %}
                        <tr>
                            <td>{{ offre.libelle }}</td>
                            <td>{{ offre.typeOffre.libelle }}</td>
                            <td>{{ offre.prixMin }} € - {{ offre.prixMax }} €</td>
                            <td>
                                <turbo-frame>
                                    <a href="{{ path('app_offre_visibilite', {'id':offre.id}) }}">
                                        <button class="btn
                                        {% if offre.visible == true %}
                                    btn-success">
                                            Masquer
                                            {% else %}
                                                btn-danger">
                                                Rendre visible
                                            {% endif %}
                                        </button>
                                    </a>
                                </turbo-frame>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </template>
</turbo-stream>