src/Entity/BesoinRole.php
<?php

namespace App\Entity;

use App\Repository\BesoinRoleRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: BesoinRoleRepository::class)]
#[Broadcast]
class BesoinRole
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $nb_jours = null;

    #[ORM\ManyToOne(inversedBy: 'besoinRoles')]
    private ?Role $role = null;

    #[ORM\ManyToOne(inversedBy: 'besoin_role')]
    private ?Offre $offre = null;

    #[ORM\Column]
    private ?int $nb_jours_estime_min = null;

    #[ORM\Column]
    private ?int $nb_jours_estime_max = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbJours(): ?int
    {
        return $this->nb_jours;
    }

    public function setNbJours(int $nb_jours): static
    {
        $this->nb_jours = $nb_jours;

        return $this;
    }

    public function getRole(): ?Role
    {
        return $this->role;
    }

    public function setRole(?Role $role): static
    {
        $this->role = $role;

        return $this;
    }

    public function getOffre(): ?Offre
    {
        return $this->offre;
    }

    public function setOffre(?Offre $offre): static
    {
        $this->offre = $offre;

        return $this;
    }

    public function getNbJoursEstimeMin(): ?int
    {
        return $this->nb_jours_estime_min;
    }

    public function setNbJoursEstimeMin(int $nb_jours_estime_min): static
    {
        $this->nb_jours_estime_min = $nb_jours_estime_min;

        return $this;
    }

    public function getNbJoursEstimeMax(): ?int
    {
        return $this->nb_jours_estime_max;
    }

    public function setNbJoursEstimeMax(int $nb_jours_estime_max): static
    {
        $this->nb_jours_estime_max = $nb_jours_estime_max;

        return $this;
    }
}

src/Controller/Phase2A/JoueurPhase2AController.php
<?php

namespace App\Controller\Phase2A;

use App\Entity\AssigneRole;
use App\Entity\Game;
use App\Entity\Projet;
use App\Form\AssigneRoleType;
use App\Form\ProjetType;
use App\Repository\AssigneRoleRepository;
use App\Repository\ProfilRepository;
use App\Repository\ProjetRepository;
use App\Repository\PropositionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Mercure\HubInterface;
use Symfony\Component\Mercure\Update;

class JoueurPhase2AController extends AbstractController
{
    public function __construct(
        private HubInterface          $hub,
        private PropositionRepository $propositionRepository,
        private ProjetRepository      $projetRepository,
        private AssigneRoleRepository $assigneRoleRepository,
        private ProfilRepository      $profilRepository,
    )
    {
    }

    public function index(?Game $game): void
    {
        // récupérer toutes les équipes de la game
        $equipes = $game->getEquipes();

        // envoyer une mise à jour Mercure pour chaque équipe
        foreach ($equipes as $equipe) {
            $propositions = $this->propositionRepository->findBy(['equipe' => $equipe]);

            foreach ($propositions as $proposition) {
                // si il n'existe pas encore de projet pour cette offre et cette équipe
                if ($this->projetRepository->findOneBy(['offre' => $proposition->getOffre(), 'equipe' => $equipe]) === null && $proposition->isEtat() === true) {
                    $projet = new Projet();
                    $projet->setEquipe($equipe);
                    $projet->setOffre($proposition->getOffre());
                    $projet->setDebut($game->getPeriode());
                    $projet->setFin($game->getPeriode() + $proposition->getOffre()->getDeadline());
                    $projet->setPrix($proposition->getPrix());


                    $proposition->setProjet($projet);
                    $this->propositionRepository->save($proposition);

                    $roles = $proposition->getOffre()->getBesoinRole();

                    foreach ($roles as $role) {
                        // si il n'existe pas encore de assigneRole pour ce projet et ce role
                        if ($this->assigneRoleRepository->findOneBy(['projet' => $projet, 'role' => $role->getRole()]) === null) {
                            $assigneRole = new AssigneRole();

                            $assigneRole->setProjet($projet);
                            $assigneRole->setRole($role->getRole());
                            $assigneRole->setNbJours($role->getNbJours());
                            $assigneRole->setNbJoursPrevi(0);
                            $projet->addAssigneRole($assigneRole);

                            $this->assigneRoleRepository->save($assigneRole);
                        }
                    }
                    $this->projetRepository->save($projet);

                } // si il existe un projet pour cette offre et cette equipe mais que l'etat de la proposition est a false
                elseif ($this->projetRepository->findOneBy(['offre' => $proposition->getOffre(), 'equipe' => $equipe]) && $proposition->isEtat() === false) {
                    $proposition->setProjet(null);
                    $this->propositionRepository->save($proposition);

                    $projet = $this->projetRepository->findOneBy(['offre' => $proposition->getOffre(), 'equipe' => $equipe]);
                    // supprimer le projet
                    $this->projetRepository->remove($projet);
                }
            }

            $projets = $this->projetRepository->findBy(['equipe' => $equipe]);

            // todo: comme pour les propositions, permettre de rester sur le même tab après une update du projet
            if ($projets !== null) {
                $projetForms = [];
                foreach ($projets as $projet) {
                    $form = $this->createForm(ProjetType::class, $projet, ['game' => $game]);
                    $projetForms[$projet->getId()] = $form->createView();
                }
            }

            $profils = $this->profilRepository->findBy(['equipe' => null]);

            $this->hub->publish(new Update(
                'game-joueur/' . $game->getId() . '/equipe/' . $equipe->getId(),
                $this->renderView('phase2a/joueur_phase2a.stream.html.twig', [
                    'game' => $game,
                    'equipe' => $equipe,
                    'projetForms' => $projetForms ?? null,
                    'profils' => $profils ?? null,
                ]),
                false
            ));
        }
    }
}

src/Controller/Phase2A/MaitrePhase2AController.php
<?php

namespace App\Controller\Phase2A;

use App\Entity\Game;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Mercure\HubInterface;
use Symfony\Component\Mercure\Update;

class MaitrePhase2AController extends AbstractController
{
    public function __construct(
        private UserRepository $userRepository,
        private HubInterface    $hub,
    )
    {
    }

    public function index(?Game $game, ?array $equipes)
    {
        $maitres = $this->userRepository->findByGameAndRole($game, 'ROLE_MAITRE');

        foreach ($maitres as $maitre) {
            $this->hub->publish(new Update(
                'game-maitre/' . $maitre->getId(),
                $this->renderView('phase2a/maitre_phase2a.stream.html.twig', [
                    'game' => $game,
                    'equipes' => $equipes,
                    'maitre' => $maitre,
                    'projetUpdated' => $projetUpdated ?? null,
                ]),
                false
            ));
        }
    }
}

templates/phase2a/maitre_phase2a.stream.html.twig
<turbo-stream action="replace" target="phase">
    <template>
        <div id="phase" {{ turbo_stream_listen('game-maitre/'~maitre.id) }}>

            <ul class="nav nav-tabs" id="myTab" role="tablist">
                {% for equipe in equipes %}
                    <li class="nav-item" role="presentation">
                        <a class="nav-link
                        {# {% if offreUpdated is defined and offreUpdated == offre %}active{% elseif offreUpdated is not defined and loop.first %}active{% endif %} #}
                         {% if loop.first %}active{% endif %}"
                           id="equipe-{{ equipe.id }}-tab"
                           data-bs-toggle="tab" href="#equipe-{{ equipe.id }}" role="tab"
                           aria-controls="equipe-{{ equipe.id }}"
                           aria-selected="{% if loop.first %}true{% else %}false{% endif %}">{{ equipe.nom }}</a>
                    </li>
                {% endfor %}
            </ul>

            <div class="tab-content" id="myTabContent">
                {% for equipe in equipes %}
                    <div class="card tab-pane fade
                {#                    {% if equipeUpdated is defined and equipeUpdated == equipe %}show active{% elseif equipeUpdated is not defined and loop.first %}show active{% endif %} #}
                {% if loop.first %}show active{% endif %}"
                         id="equipe-{{ equipe.id }}"
                         role="tabpanel" aria-labelledby="equipe-{{ equipe.id }}-tab">
                        <div class="card-body">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>
                                        Projet
                                    </th>
                                    {% for role in game.roles %}
                                        <th>
                                            {{ role.libelle }}
                                        </th>
                                    {% endfor %}
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                        <small class="text-muted">
                                            Tâches récurrentes
                                        </small>
                                    </td>
                                    {% for role in game.roles %}
                                        <td>
                                            <small class="text-muted">
                                                {{ role.tacheRecurrente }} jr(s)
                                            </small>
                                        </td>
                                    {% endfor %}
                                </tr>

                                {% for projet in equipe.projets %}
                                    <tr>
                                        <th>
                                            {{ projet.offre.libelle }} <br>
                                            <small class="text-muted">
                                                échéance :
                                                {% if projet.fin == 1 %}
                                                    janvier
                                                {% elseif projet.fin == 2 %}
                                                    février
                                                {% elseif projet.fin == 3 %}
                                                    mars
                                                {% elseif projet.fin == 4 %}
                                                    avril
                                                    {% elseif projet.fin == 5 %}
                                                    mai
                                                {% elseif projet.fin == 6 %}
                                                    juin
                                                {% elseif projet.fin == 7 %}
                                                    juillet
                                                {% endif %}
                                            </small>
                                        </th>
                                        {% for assigneRole in projet.assigneRoles %}
                                            <td>
                                                {{ assigneRole.nbJoursPrevi }} jours saisis
                                                <br>
                                                <small class="text-muted">
                                                    {{ assigneRole.nbJours }} jours restants sur
                                                    {% for besoinRole in projet.offre.besoinRole %}
                                                        {% if besoinRole.role == assigneRole.role %}
                                                            {{ besoinRole.nbJours }}
                                                        {% endif %}
                                                    {% endfor %}
                                                </small>
                                            </td>
                                        {% endfor %}
                                    </tr>
                                {% endfor %}
                                <tr>
                                    <th>
                                        Capacité
                                    </th>

                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

    </template>
</turbo-stream>